services:
  node:
    image: ghcr.io/archisinal/marketplace-contracts-node:latest
    command: /usr/local/cargo/bin/substrate-contracts-node --dev --unsafe-rpc-external --rpc-cors=all --base-path=/tmp/archisinal-marketplace
    ports:
      - "9944:9944"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/marketplace
    command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 60s yarn migrate:dev"

  indexer:
    build:
      context: .
      dockerfile: indexer.Dockerfile
    depends_on:
      - db
      - node
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/marketplace
      RPC_URL: ws://node:9944
    command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 60s yarn start"
    ports:
      - "3020:3020"

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/marketplace
    ports:
      - "3010:3010"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - db
      - backend
      - indexer
    environment:
      NEXT_PUBLIC_INDEXER_WS_URL: ws://indexer:3020
      NEXT_PUBLIC_RPC_URL: ws://node:9944
      NEXT_PUBLIC_BACKEND_URL: http://backend:3010
    ports:
      - "3000:3000"

volumes:
  pgdata:
