version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - pgdata:/var/lib/postgresql/data

  marketplace-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/marketplace
      DO_MIGRATE: "true"
      DO_SEED: "true"
    ports:
      - "3000:3000"

volumes:
  pgdata:
