export const FieldNames = {
    drawingName: 'drawingName',
    description: 'description',
    revisionNumber: 'revisionNumber',
    construction: 'construction',
    category: 'category',
    showContact: 'showContact',
    showPortfolio: 'showPortfolio',
    priceType: 'priceType',
    price: 'price',
    royalties: 'royalties',
    minimumBid: 'minimumBid',
    instantPurchase: 'instantPurchase',
    startingDate: 'startingDate',
    endDate: 'endDate',
    displayName: 'displayName',
    symbol: 'symbol',
}
