import { auctionData } from '../mockData/auctionItems'
export const collectionData = [
    {
        itemName: 'Architecture Home',
        itemImg: '/mockCategories/Rectangle 41.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Zombi Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 15,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Dobby Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -18,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Xena Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 20,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Santa Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Terminator Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 5,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Dracula Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Da Vinchi Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Baby Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Avatar Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Oxygen Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Stimorol Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Dwarf Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Capitan Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Dr Mayers Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Rocket Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Duda Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Architecture Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
    {
        itemName: 'Architecture Home',
        itemImg: '/mockCategories/Rectangle 42.png',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
        collectionItems: auctionData
    },
]
