export const collectionData = [
    {
        itemName: 'Architecture Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Zombi Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 15,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Dobby Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -18,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Xena Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 20,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Santa Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Terminator Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: 5,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Dracula Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Da Vinchi Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Baby Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Avatar Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Oxygen Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Stimorol Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Dwarf Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Capitan Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Dr Mayers Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Rocket Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Duda Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Architecture Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
    {
        itemName: 'Architecture Home',
        floorPrice: 57.5,
        currency: 'ASTR',
        floorChange: -8,
        volume: 1275,
        sales: 55,
        items: '10K',
        owners: '6K',
    },
]
