export const FieldNames = {
  projectName: 'projectName',
  description: 'description',
  revisionNumber: 'revisionNumber',
  construction: 'construction',
  category: 'category',
  showContact: 'showContact',
  showPortfolio: 'showPortfolio',
  listingType: 'listingType',
  price: 'price',
  minimumBid: 'minimumBid',
  instantPurchase: 'instantPurchase',
  startingDate: 'startingDate',
  endDate: 'endDate',
  displayName: 'displayName',
  collectionRoyalty: 'collectionRoyalty',
  nftRoyalty: 'nftRoyalty',
  selectedCollectionId: 'selectedCollectionId',
  categories: 'categories',
  nftImage: 'nftImage',
  nftProject: 'nftProject',
  startPrice: 'startPrice',
};
